"""update

Revision ID: 24002cb96650
Revises: d4901f0d55e5
Create Date: 2018-11-15 10:39:11.509794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24002cb96650'
down_revision = 'd4901f0d55e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacxin')
    op.drop_column('donvi', 'id_mevabe')
    op.drop_column('donvi', 'password_mevabe')
    op.add_column('user', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('fullname', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('macongdan', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user', ['macongdan'])
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'macongdan')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'fullname')
    op.drop_column('user', 'first_name')
    op.add_column('donvi', sa.Column('password_mevabe', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('donvi', sa.Column('id_mevabe', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_table('vacxin',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('ma', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ten', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('mota', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vacxin_pkey'),
    sa.UniqueConstraint('ma', name='vacxin_ma_key')
    )
    # ### end Alembic commands ###
