"""init db

Revision ID: 38a5f9824ec3
Revises: b14d6088b40f
Create Date: 2018-11-19 13:58:41.616735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a5f9824ec3'
down_revision = 'b14d6088b40f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
