"""init db

Revision ID: 3ffaf6ffe3f7
Revises: 38a5f9824ec3
Create Date: 2018-11-19 13:59:06.748854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ffaf6ffe3f7'
down_revision = '38a5f9824ec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
