import uuid

from application.database import db
from application.database.model import CommonModel
from PIL.JpegImagePlugin import COM
from sqlalchemy import (DECIMAL, Boolean, Column, Date, DateTime, Float,ForeignKey, Integer, String, Text,JSON, UniqueConstraint)
from sqlalchemy.dialects.postgresql import  UUID
from sqlalchemy.orm import *
# from sqlalchemy import *
from sqlalchemy.orm import backref, relationship
from sqlalchemy.orm.collections import attribute_mapped_collection

def default_uuid():
    return str(uuid.uuid4())


##Mau 1:
class KiemTraTinhTrangVSS(CommonModel):
    __tablename__ = 'kiemtratinhtrangvss'
    id = db.Column(UUID(as_uuid=True), primary_key=True,default=default_uuid)
    tenphuluc = db.Column(db.String)
    thongtu = db.Column(db.String)
    tieuchichinh = db.Column(db.String)
    tieuchichinhkdat = db.Column(db.String)
    babexuly = db.Column(db.String)
    baexulykdat = db.Column(db.String)
    lapbechuaphan = db.Column(db.String)
    lapbechuaphankdat = db.Column(db.String)
    matsannhan = db.Column(db.String)
    matsannhankdat = db.Column(db.String)
    besiconutnuoc = db.Column(db.String)
    besiconutnuockdat = db.Column(db.String)
    coongthonghoi = db.Column(db.String)
    coongthonghoikdat = db.Column(db.String)
    codunuocdoi = db.Column(db.String)
    codunuocdoikdat = db.Column(db.String)
    dungcuchuanuocdoi = db.Column(db.String)
    dungcuchuanuocdoikdat = db.Column(db.String)
    kcomuihoi = db.Column(db.String)
    kcomuihoikdat = db.Column(db.String)
    nuocxuli = db.Column(db.String)
    nuocxulikdat = db.Column(db.String)
    vsxungquanh = db.Column(db.String)
    vsxungquanhkdat = db.Column(db.String)

    cactieuchiphu = db.Column(db.String)
    cactieuchiphukdat = db.Column(db.String)
    matsannhatieu = db.Column(db.String)
    matsannhatieukdat = db.Column(db.String)
    giayvesinh = db.Column(db.String)
    giayvesinhkdat = db.Column(db.String)
    kcoruoi = db.Column(db.String)
    kcoruoikdat = db.Column(db.String)
    bexinuoc = db.Column(db.String)
    bexinuockdat = db.Column(db.String)
    dcchekin = db.Column(db.String)
    dcchekinkdat = db.Column(db.String)
    vesinhxungquanh = db.Column(db.String)
    vesinhxungquanhkdat = db.Column(db.String)

    hopvs = db.Column(db.String)
    kohopvs = db.Column(db.String)
    nhatieukodatbatieuchi = db.Column(db.String)

##Mau 2
class NhaTieuThamNuoc(CommonModel):
    __tablename__ = 'nhatieuthamnuoc'
    id = db.Column(UUID(as_uuid=True), primary_key=True,default=default_uuid)
    tenphuluc = db.Column(db.String)
    thongtu = db.Column(db.String)
    tieuchichinh = db.Column(db.String)
    tieuchichinhkdat = db.Column(db.String)
    babexuly = db.Column(db.String)
    baexulykdat = db.Column(db.String)
    lapbechuaphan = db.Column(db.String)
    lapbechuaphankdat = db.Column(db.String)
    matsannhan = db.Column(db.String)
    matsannhankdat = db.Column(db.String)
    besiconutnuoc = db.Column(db.String)
    besiconutnuockdat = db.Column(db.String)
    coongthonghoi = db.Column(db.String)
    coongthonghoikdat = db.Column(db.String)
    codunuocdoi = db.Column(db.String)
    codunuocdoikdat = db.Column(db.String)
    dungcuchuanuocdoi = db.Column(db.String)
    dungcuchuanuocdoikdat = db.Column(db.String)
    kcomuihoi = db.Column(db.String)
    kcomuihoikdat = db.Column(db.String)
    nuocxuli = db.Column(db.String)
    nuocxulikdat = db.Column(db.String)
    vsxungquanh = db.Column(db.String)
    vsxungquanhkdat = db.Column(db.String)
    
    cactieuchiphu = db.Column(db.String)
    cactieuchiphukdat = db.Column(db.String)
    matsannhatieu = db.Column(db.String)
    matsannhatieukdat = db.Column(db.String)
    giayvesinh = db.Column(db.String)
    giayvesinhkdat = db.Column(db.String)
    kcoruoi = db.Column(db.String)
    kcoruoikdat = db.Column(db.String)
    bexinuoc = db.Column(db.String)
    bexinuockdat = db.Column(db.String)
    dcchekin = db.Column(db.String)
    dcchekinkdat = db.Column(db.String)
    vesinhxungquanh = db.Column(db.String)
    vesinhxungquanhkdat = db.Column(db.String)

    hopvs = db.Column(db.String)
    kohopvs = db.Column(db.String)
    nhatieukodatbatieuchi = db.Column(db.String)


##Mau 3
class NhaTieu2Ngan(CommonModel):
    __tablename__ = 'nhatieu2ngan'
    id = db.Column(UUID(as_uuid=True), primary_key=True,default=default_uuid)
    tenphuluc = db.Column(db.String)
    thongtu = db.Column(db.String)
    tieuchichinh = db.Column(db.String)
    tieuchichinhkdat = db.Column(db.String)
    babexuly = db.Column(db.String)
    baexulykdat = db.Column(db.String)
    lapbechuaphan = db.Column(db.String)
    lapbechuaphankdat = db.Column(db.String)
    matsannhan = db.Column(db.String)
    matsannhankdat = db.Column(db.String)
    besiconutnuoc = db.Column(db.String)
    besiconutnuockdat = db.Column(db.String)
    coongthonghoi = db.Column(db.String)
    coongthonghoikdat = db.Column(db.String)
    codunuocdoi = db.Column(db.String)
    codunuocdoikdat = db.Column(db.String)
    dungcuchuanuocdoi = db.Column(db.String)
    dungcuchuanuocdoikdat = db.Column(db.String)
    kcomuihoi = db.Column(db.String)
    kcomuihoikdat = db.Column(db.String)
    nuocxuli = db.Column(db.String)
    nuocxulikdat = db.Column(db.String)
    vsxungquanh = db.Column(db.String)
    vsxungquanhkdat = db.Column(db.String)

    cactieuchiphu = db.Column(db.String)
    cactieuchiphukdat = db.Column(db.String)
    matsannhatieu = db.Column(db.String)
    matsannhatieukdat = db.Column(db.String)
    giayvesinh = db.Column(db.String)
    giayvesinhkdat = db.Column(db.String)
    kcoruoi = db.Column(db.String)
    kcoruoikdat = db.Column(db.String)
    bexinuoc = db.Column(db.String)
    bexinuockdat = db.Column(db.String)
    dcchekin = db.Column(db.String)
    dcchekinkdat = db.Column(db.String)
    vesinhxungquanh = db.Column(db.String)
    vesinhxungquanhkdat = db.Column(db.String)
    ongthonghoi = db.Column(db.String)
    ongthonghoikdat = db.Column(db.String)
    nganmua = db.Column(db.String)
    nganmuakdat = db.Column(db.String)

    hopvs = db.Column(db.String)
    kohopvs = db.Column(db.String)
    nhatieukodatbatieuchi = db.Column(db.String)


##Mau 4
class NhaTieuChim(CommonModel):
    __tablename__ = 'nhatieuchim'
    id = db.Column(UUID(as_uuid=True), primary_key=True,default=default_uuid)
    tenphuluc = db.Column(db.String)
    thongtu = db.Column(db.String)
    tieuchichinh = db.Column(db.String)
    tieuchichinhkdat = db.Column(db.String)
    babexuly = db.Column(db.String)
    baexulykdat = db.Column(db.String)
    lapbechuaphan = db.Column(db.String)
    lapbechuaphankdat = db.Column(db.String)
    matsannhan = db.Column(db.String)
    matsannhankdat = db.Column(db.String)
    besiconutnuoc = db.Column(db.String)
    besiconutnuockdat = db.Column(db.String)
    coongthonghoi = db.Column(db.String)
    coongthonghoikdat = db.Column(db.String)
    codunuocdoi = db.Column(db.String)
    codunuocdoikdat = db.Column(db.String)
    dungcuchuanuocdoi = db.Column(db.String)
    dungcuchuanuocdoikdat = db.Column(db.String)
    kcomuihoi = db.Column(db.String)
    kcomuihoikdat = db.Column(db.String)
    nuocxuli = db.Column(db.String)
    nuocxulikdat = db.Column(db.String)
    vsxungquanh = db.Column(db.String)
    vsxungquanhkdat = db.Column(db.String)
    chekinnangmua = db.Column(db.String)
    chekinnangmuakdat = db.Column(db.String)

    cactieuchiphu = db.Column(db.String)
    cactieuchiphukdat = db.Column(db.String)
    matsannhatieu = db.Column(db.String)
    matsannhatieukdat = db.Column(db.String)
    giayvesinh = db.Column(db.String)
    giayvesinhkdat = db.Column(db.String)
    kcoruoi = db.Column(db.String)
    kcoruoikdat = db.Column(db.String)
    bexinuoc = db.Column(db.String)
    bexinuockdat = db.Column(db.String)
    dcchekin = db.Column(db.String)
    dcchekinkdat = db.Column(db.String)
    vesinhxungquanh = db.Column(db.String)
    vesinhxungquanhkdat = db.Column(db.String)

    hopvs = db.Column(db.String)
    kohopvs = db.Column(db.String)
    nhatieukodatbatieuchi = db.Column(db.String)

##Mau 5
class ChoTruongHocTramYTE(CommonModel):
    __tablename__ = 'chotruonghoctramyte'
    id = db.Column(UUID(as_uuid=True), primary_key=True,default=default_uuid)
    ctmot = db.Column(db.String)
    cthai = db.Column(db.String)
    ctba = db.Column(db.String)
    ctbon = db.Column(db.String)
    ctnam = db.Column(db.String)
    ctsau = db.Column(db.String)
    ctbay = db.Column(db.String)
    cttam = db.Column(db.String)
    ctchin = db.Column(db.String)
    ctmuoi = db.Column(db.String)
    ctmuoimot = db.Column(db.String)
    ctmuoihai = db.Column(db.String)
    ctmoiba = db.Column(db.String)
    ctmotbon = db.Column(db.String)
    ctmotnam = db.Column(db.String)
    ctmotsau = db.Column(db.String)
    ctmotbay = db.Column(db.String)

##Mau 6
class CacHoatDongBBC(CommonModel):
    __tablename__ = 'cachoatdongbbc'
    id = db.Column(UUID(as_uuid=True), primary_key=True,default=default_uuid)
    hoatdongtinh = db.Column(db.String)
    hoatdongtinhkdat = db.Column(db.String)
    hophoinhgi = db.Column(db.String)
    hophoinghikdat = db.Column(db.String)
    taphuan = db.Column(db.String)
    taphuankdat = db.Column(db.String)
    cachoatdong = db.Column(db.String)
    cachoatdongkdat = db.Column(db.String)
    thanhlapcuahang = db.Column(db.String)
    thanhlapcuahangkdat = db.Column(db.String)
    taphuantruyenthong = db.Column(db.String)
    taphuantruyenthongkdat = db.Column(db.String)
    hdcaphuyen = db.Column(db.String)
    hdcaphuyenkdat = db.Column(db.String)
    hoptrienkhai = db.Column(db.String)
    hoptrienkhaikdat = db.Column(db.String)
    vschocanbo = db.Column(db.String)
    vschocanbokdat = db.Column(db.String)
    hdcapxa = db.Column(db.String)
    hdcapxakdat = db.Column(db.String)
    hopcapxa = db.Column(db.String)
    hopcapxakdat = db.Column(db.String)
    camketdat = db.Column(db.String)
    camketdatkdat = db.Column(db.String)
    vstx = db.Column(db.String)
    truyenthongthon = db.Column(db.String)
    truonghoc = db.Column(db.String)
    bancamket = db.Column(db.String)
    
